import type { VehicleModel } from './types';

export const dealershipModels: Record<string, VehicleModel[]> = {
  honda: [
    { name: 'Accord', category: 'Cars' },
    { name: 'Accord Hybrid', category: 'Electric / Hybrid' },
    { name: 'Civic', category: 'Cars' },
    { name: 'Civic Hatchback', category: 'Cars' },
    { name: 'Civic Sedan', category: 'Cars' },
    { name: 'Civic Sedan Hybrid', category: 'Electric / Hybrid' },
    { name: 'Civic Si Coupe', category: 'Cars' },
    { name: 'Civic Si Sedan', category: 'Cars' },
    { name: 'Civic Type R', category: 'Cars' },
    { name: 'CR-V', category: 'SUVs / Crossovers' },
    { name: 'CR-V Hybrid', category: 'Electric / Hybrid' },
    { name: 'HR-V', category: 'SUVs / Crossovers' },
    { name: 'Odyssey', category: 'Minivan / Truck' },
    { name: 'Passport', category: 'SUVs / Crossovers' },
    { name: 'Pilot', category: 'SUVs / Crossovers' },
    { name: 'Prologue', category: 'Electric / Hybrid' },
    { name: 'Ridgeline', category: 'Minivan / Truck' }
  ],
  chevrolet: [
    { name: 'Blazer', category: 'New Vehicles' },
    { name: 'Blazer EV', category: 'New Vehicles' },
    { name: 'Bolt EUV', category: 'New Vehicles' },
    { name: 'Bolt EV', category: 'New Vehicles' },
    { name: 'Camaro', category: 'New Vehicles' },
    { name: 'Colorado', category: 'New Vehicles' },
    { name: 'Corvette', category: 'New Vehicles' },
    { name: 'Equinox', category: 'New Vehicles' },
    { name: 'Equinox EV', category: 'New Vehicles' },
    { name: 'Express Cargo', category: 'Commercial' },
    { name: 'Express Cutaway', category: 'Commercial' },
    { name: 'Express Passenger', category: 'Commercial' },
    { name: 'Low Cab Forward', category: 'Commercial' },
    { name: 'Malibu', category: 'New Vehicles' },
    { name: 'Silverado 1500', category: 'New Vehicles' },
    { name: 'Silverado 1500 LTD', category: 'New Vehicles' },
    { name: 'Silverado 2500 HD', category: 'New Vehicles' },
    { name: 'Silverado 3500 Chassis Cab', category: 'Commercial' },
    { name: 'Silverado 3500 HD', category: 'New Vehicles' },
    { name: 'Silverado 4500 HD', category: 'Commercial' },
    { name: 'Silverado 5500 HD', category: 'Commercial' },
    { name: 'Silverado 6500 HD', category: 'Commercial' },
    { name: 'Silverado EV', category: 'New Vehicles' },
    { name: 'Suburban', category: 'New Vehicles' },
    { name: 'Tahoe', category: 'New Vehicles' },
    { name: 'Trailblazer', category: 'New Vehicles' },
    { name: 'Traverse', category: 'New Vehicles' },
    { name: 'Traverse Limited', category: 'New Vehicles' },
    { name: 'Trax', category: 'New Vehicles' }
  ],
  toyota: [
    { name: '4Runner', category: 'New Vehicles' },
    { name: 'bZ4X', category: 'New Vehicles' },
    { name: 'Camry', category: 'Cars & Minivans' },
    { name: 'Corolla', category: 'Cars & Minivans' },
    { name: 'Corolla Cross', category: 'Crossovers & SUVs' },
    { name: 'Corolla Cross Hybrid', category: 'Electrified' },
    { name: 'Corolla Hatchback', category: 'Cars & Minivans' },
    { name: 'Corolla Hybrid', category: 'Electrified' },
    { name: 'GR Corolla', category: 'Cars & Minivans' },
    { name: 'GR Supra', category: 'Cars & Minivans' },
    { name: 'GR86', category: 'Cars & Minivans' },
    { name: 'Grand Highlander', category: 'Crossovers & SUVs' },
    { name: 'Grand Highlander Hybrid', category: 'Electrified' },
    { name: 'Highlander', category: 'Crossovers & SUVs' },
    { name: 'Highlander Hybrid', category: 'Electrified' },
    { name: 'Land Cruiser', category: 'Crossovers & SUVs' },
    { name: 'Prius', category: 'Electrified' },
    { name: 'Prius Prime', category: 'Electrified' },
    { name: 'RAV4', category: 'Crossovers & SUVs' },
    { name: 'RAV4 Hybrid', category: 'Electrified' },
    { name: 'RAV4 Prime', category: 'Electrified' },
    { name: 'Sequoia', category: 'Crossovers & SUVs' },
    { name: 'Sienna', category: 'Cars & Minivans' },
    { name: 'Tacoma', category: 'Trucks' },
    { name: 'Tacoma i-FORCE MAX', category: 'Trucks' },
    { name: 'Toyota Crown', category: 'Cars & Minivans' },
    { name: 'Toyota Crown Signia', category: 'Cars & Minivans' },
    { name: 'Tundra', category: 'Trucks' },
    { name: 'Tundra i-FORCE MAX', category: 'Trucks' },
    { name: 'Venza', category: 'Crossovers & SUVs' }
  ],
};